## Problem-Solving with NumPy


#### 1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’

`Input`:
arr = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])
target = 7
foo_1(arr, target)

`Output`:
[2 3 4 5 6 8 7 1 9 0]

`Input`:
arr = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])
target = 11
foo_1(arr, target)

`Output`:
’no item found’


In [39]:
import numpy as np

In [41]:
def foo_1(arr, target):
    if target not in arr:
        return 'no item found'
    
    indices = np.abs(arr - target).argmin()
    return indices
arr = np.array([1, 3, 5, 7,8,6,7,7,3,8,3,7, 9])
target = 11
result = foo_1(arr, target)
print(result)

no item found


#### 2. Write a user defined function foo_2 that takes a 1 or 2 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis.
Input`:
arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])
foo_2(arr, axis = 0)

`Output`:
[4 1 2]


foo_2(arr, axis = 1)
`Output`:
[2 2 2 1]


arr1 = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]],

                [[2, 0, 1, 0],
                 [0, 5, 0, 0],
                 [1, 2, 3, 4]])

foo_2(arr1 , axis = 0)

`Output`:
[[7],
[7]]

foo_2(arr1 , axis = 1)

`Output`:
[[4 1 2],
[2 1 4]]

foo_2(arr1 , axis = 2)
`Output`:
[[2 2 2 1],
[2 2 2 1]]


In [42]:
def foo_2(arr, axis):
    if arr.ndim != 2:
        print("Input array must be 2-dimensional")
    else:
        x=np.where(arr != 0, 1, 0)
        counts=np.sum(x,axis=axis)
        return counts
def foo_3(arr, axis):
    if arr.ndim != 3:
        print("Input array must be 3-dimensional")
    else:
        x=np.where(arr != 0, 1, 0)
        counts=np.sum(x,axis=axis)
        return counts

In [43]:
arr=np.array([[1,2,3,4],[0,5,0,0],[2,0,1,0]])
foo_2(arr,axis=0)

array([2, 2, 2, 1])

#### 3. 1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array

   data=np.array([[85,89,88],
                 [78,89,94],
                 [91,87,90],
                 [87,95,84]])

In [44]:
data=np.array([[85,88,89],[78,89,94],[91,87,90],[87,95,84]])
data

array([[85, 88, 89],
       [78, 89, 94],
       [91, 87, 90],
       [87, 95, 84]])

In [45]:
def foo_2(array):
    x=np.any(data>90,axis=1)
    result=array[x]
    print('stu who scored grater than 90:')
    print(result)
foo_2(data)

stu who scored grater than 90:
[[78 89 94]
 [91 87 90]
 [87 95 84]]


#### 3. 2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.

      data=np.array([[120,150,130,110],
                     [200,180,220,250],
                     [90,100,95,110],
                     [300,280,320,340]])


In [46]:
data=np.array([[120,150,130,110],[200,180,220,250],[90,100,95,110],[300,280,320,340]])
data

array([[120, 150, 130, 110],
       [200, 180, 220, 250],
       [ 90, 100,  95, 110],
       [300, 280, 320, 340]])

In [47]:
product1=data[0,:]
product2=data[1,:]
product3=data[2,:]
product4=data[3,:]

print(f'the mean of product1 is: {np.mean(product1)}')
print(f'the mean of product2 is: {np.mean(product2)}')
print(f'the mean of product3 is: {np.mean(product3)}')
print(f'the mean of product4 is: {np.mean(product4)}')

the mean of product1 is: 127.5
the mean of product2 is: 212.5
the mean of product3 is: 98.75
the mean of product4 is: 310.0


In [48]:
print(f'the median of product1 is: {np.median(product1)}')
print(f'the median of product2 is: {np.median(product2)}')
print(f'the median of product3 is: {np.median(product3)}')
print(f'the median of product4 is: {np.median(product4)}')

the median of product1 is: 125.0
the median of product2 is: 210.0
the median of product3 is: 97.5
the median of product4 is: 310.0


In [49]:
print(f'the std of product1 is: {np.std(product1)}')
print(f'the std of product2 is: {np.std(product2)}')
print(f'the std of product3 is: {np.std(product3)}')
print(f'the std of product4 is: {np.std(product4)}')

the std of product1 is: 14.79019945774904
the std of product2 is: 25.8602010819715
the std of product3 is: 7.39509972887452
the std of product4 is: 22.360679774997898


In [50]:
fst_mnth=data[:,0]
scnd_mnth=data[:,1]
thrd_mnth=data[:,2]
frth_mnth=data[:,3]

print(f'1stmonth of sale:{np.sum(fst_mnth)}')
print(f'2ndmonth of sale:{np.sum(scnd_mnth)}')
print(f'3rdmonth of sale:{np.sum(thrd_mnth)}')
print(f'4thmonth of sale:{np.sum(frth_mnth)}')

1stmonth of sale:710
2ndmonth of sale:710
3rdmonth of sale:765
4thmonth of sale:810


#### 3. 3 Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.



In [51]:
array=np.random.randint(1,100,size=1000)
print(array)

[24 34 84 24 98 94 59 51 85 51 53 14 83 24  3 73 70 89 66 50 25 43 72  8
 62 95 15 93 49 12 72 65 36 86  9 16 80 17 62 76 94 65 65 41 65 64  4 93
  4 90 18 95 78 43 37 67 74 54 88 11 34 15 23  7 83 18 37 62 93  7 38  7
  8 56 76 51 72 20 24 22 22 48  9 13 37  6  2 87  1 13 14 26 67 87 34  9
 53 19 59 22 66 12 54 37 59 73 40 78 68 21  4 61 61 88 19 69  1 94 24 11
 35 35 55 89 76 15 10 53 64 81 12 91 17 67 43 33 59  7  5 51 31 47 95 57
 82 64 68  7  4 76  6 53 62 63 65 31 84 14 70 42 71 17 18 57 33 68 61 28
 85 62 40 38 16 47 95 46 62 11 96 51 96 20 57 80 12 94 30 98 52 72 26  3
 54 74 19 48 38 96 82 34 89  1 32 98 37 60 65 56 52 58 54 31 59 27  1 32
 91 67 81 50 36 42 98 39 19 20 68 12 39 46 50 76 85 42 80 72 53 20 98 77
 81  6 34 84 59 25 37 94 88  5 31 51 74 63 58 15 78  7 52 43 58 31 42 48
 79 54 29  2 96 52 47 34 94 17 84 96 57 85 40 47 68 69 24 54 79 38  8 97
 21 10 97 88 49 71 56 22 81 59 71 57 95 21 70 73 79 30 19 15 49 27  5 51
 55 39 64  1 89 54 76 94 75 28 12 57 52 51 24 54 97

In [52]:
unique_values, counts = np.unique(array, return_counts=1)

sorted_indices = np.argsort(counts)[::-1]

top_values = unique_values[sorted_indices[:10]]
top_counts = counts[sorted_indices[:10]]


In [53]:
print("Top 10 most frequently occurring values:")
for value, count in zip(top_values, top_counts):
    print(f"{value}: {count} occurrences")

Top 10 most frequently occurring values:
19: 18 occurrences
65: 18 occurrences
24: 17 occurrences
52: 17 occurrences
20: 17 occurrences
1: 17 occurrences
12: 16 occurrences
59: 16 occurrences
77: 16 occurrences
64: 15 occurrences
